[package]
name = "gearbox"
version = "0.1.0"
edition = "2024"

[dependencies]
anarchy = { path = "../anarchy" }
cell = { path = "../cell" }
magician-vgpu = { path = "../shader_magician/magician-vgpu" }
mutual = "1.0.2"
shaders = { path = "./shaders" }

winit = { version = "0.30", features = ["android-native-activity"] }
wgpu = "29.0"
bytemuck = "1.25.0"
ahash = { version = "0.8.12", default-features = false, features = ["std", "compile-time-rng"] }
derive_more = "2.1.1"
tobj = "3.2"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg", "tga", "bmp", "dds", "farbfeld", "hdr", "ico", "openexr", "pnm", "qoi", "tiff", "webp"]

[dev-dependencies]
pollster = "1.0.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ureq = "3.3.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
web-sys = { version = "0.3.103", features = ["Window", "Location", "Request", "RequestInit", "RequestMode", "Response"] }
js-sys = "0.3.103"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
